### ISSUE TITLE
Copy files does not work for all of the repo's

### ISSUE THREAD

**Issue by Tjitse-E** [derberg/copy-files-to-other-repositories#43]
#### Describe the bug
I'm updating about 40 repo's at once with this Github action, after inspecting the logs i'm seeing that some repo's are skipped:

```
Started updating *** repo
  Cloning https://github.com/***
  Checking if repo initialized.
  Getting list of branches the action should operate on
  Getting list of all the branches for the repository
  These were requested branches: ^development$
  This is default branch: development
  These is a final list of branches action will operate on: []
  Repo has no branches that the action could operate on
```

#### How to Reproduce
I'm not sure what causes this behaviour. Here's my workflow:

```
name: Copy global workflows

on:
  push:
    branches: [ "master" ]

jobs:
  replicate_changes:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Replicating global workflow
        uses: derberg/copy-files-to-other-repositories@v1.0.3
        with:
          branches: "^development$"
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}
          patterns_to_ignore: ".github/workflows/global_workflow_copy.yml"
          patterns_to_include: ".github/workflows"
          topics_to_include: "global-workflow"
          exclude_private: false
          exclude_forked: true
          committer_username: "TheArchitectVendic"
          committer_email: "administratie@vendic.nl"
          commit_message: "CI: Update global workflows"
```

#### Expected behavior
A PR is created for all repo's/branches  that match `^development$`.
