### ISSUE TITLE
Not able to replicate files between repositories

### ISSUE THREAD

**Issue by apetrovYa** [derberg/copy-files-to-other-repositories#63]
# Description

This is the job for syncing the repositories:

```
name: Sync GitHub Directory Workflow

on:
  #  push:
  #    branches:
  #      - main
  workflow_dispatch:

jobs:
  sync-repositories:
    if: github.repository == my_org_name/terraform-module-template'
    runs-on:
      group: custom-runners
    outputs:
      repositories: ${{ steps.list-repositories.outputs.repositories }}
    steps:
      - uses: actions/checkout@v3
      - uses: derberg/manage-files-in-multiple-repositories@v2.0.0
        with:
          github_token: ${{ secrets.GH_API_TOKEN }}
          patterns_to_include: '.github'
          destination: '.github'
          # Repository Labels Very Important
          topics_to_include: terraform-module
          repos_to_ignore: terraform-module-template
          exclude_forked: true
          committer_username: ci
          committer_email: no-reply@github.com
          commit_message: "ci: replicating the .github directory from the terraform-module-template repository"
```

This is the log I get at run time: 

```
Warning: Failed replicating files for this repo: Error: ENOENT: no such file or directory, unlink '/home/runner/_work/terraform-module-template/terraform-module-template/clones/terraform-aws-rds-pg-groups/.github/dependabot.yaml'
```

The GitHub token has the necessary permissions to be able to manage Git repositories within the organisation.

Much appreciated any help!

N.B. The GitHub runners are self-hosted in a Kubernetes cluster through the `arc-gha-rs-controller` Kubernetes controller.
